source "https://rubygems.org"

group :test do
  gem "rake"
  gem "puppet", ENV['PUPPET_VERSION'] || '~> 3.7.0'
  gem "rspec-puppet", :git => 'https://github.com/rodjek/rspec-puppet.git'
  gem "puppetlabs_spec_helper"
  gem "metadata-json-lint"
  gem "rspec-puppet-facts"
end

group :development do
  gem "travis"
  gem "travis-lint"
  gem "vagrant-wrapper"
  gem "puppet-blacksmith"

  # Fixing version to < 2.8 to avoid duplicate directory errors caused by the fixture symlinking
  # see https://github.com/guard/listen/wiki/Duplicate-directory-errors
  gem 'listen', '~>2.7.12'
  gem "guard-rspec"
end

group :system_tests do
  gem "beaker"
  gem "beaker-rspec"
end
